import Link from "next/link";
import { Archive, Copy, Eye, MoreHorizontal, Pause, Play, Trash2 } from "lucide-react";
import type { Campaign, Platform } from "@/features/ads/types";
import { campaignStatusStyle } from "./CampaignRow";

interface Props { campaign: Campaign; platform: Platform; selected: boolean; onSelect: () => void; onAction: (action: string) => void; }
export function CampaignCard({ campaign, platform, selected, onSelect, onAction }: Props) {
  return <div className={`rounded-3xl border bg-slate-900/75 p-5 transition duration-300 hover:-translate-y-1 hover:border-cyan-500/30 ${selected ? "border-cyan-500/50" : "border-slate-800"}`}>
    <div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl text-xs font-bold" style={{ backgroundColor: `${platform.color}20`, color: platform.color }}>{platform.shortName}</span><div><p className="text-xs text-slate-500">{platform.name}</p><span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[11px] ${campaignStatusStyle[campaign.status]}`}>{campaign.status}</span></div></div><div className="flex items-center gap-2"><input type="checkbox" checked={selected} onChange={onSelect} className="size-4 accent-cyan-400" /><details className="relative"><summary className="list-none cursor-pointer text-slate-500 hover:text-white"><MoreHorizontal size={18} /></summary><div className="absolute right-0 z-30 mt-1 w-40 rounded-xl border border-slate-700 bg-slate-900 p-1.5 shadow-2xl">{[["View",Eye],["Edit",Eye],["Duplicate",Copy],[campaign.status === "Paused" ? "Resume" : "Pause",campaign.status === "Paused" ? Play : Pause],["Archive",Archive],["Delete",Trash2]].map(([label,Icon]) => <button key={label as string} onClick={() => onAction(label as string)} className={`flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-xs hover:bg-slate-800 ${label === "Delete" ? "text-rose-300" : "text-slate-300"}`}><Icon size={14} />{label as string}</button>)}</div></details></div></div>
    <Link href={`/dashboard/ads/campaigns/${campaign.id}`} className="mt-4 block text-base font-semibold text-white hover:text-cyan-300">{campaign.name}</Link><p className="mt-1 text-xs text-slate-500">{campaign.objective} · {campaign.owner}</p>
    <div className="mt-5 grid grid-cols-3 gap-2"><div><p className="text-xs text-slate-500">Spend</p><p className="mt-1 text-sm font-medium text-white">${campaign.spend.toLocaleString()}</p></div><div><p className="text-xs text-slate-500">Conversions</p><p className="mt-1 text-sm font-medium text-white">{campaign.conversions}</p></div><div><p className="text-xs text-slate-500">ROAS</p><p className="mt-1 text-sm font-medium text-emerald-300">{campaign.roas.toFixed(1)}x</p></div></div>
    <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${Math.min(100, (campaign.spend / campaign.budget) * 100)}%` }} /></div><p className="mt-2 text-[11px] text-slate-500">{Math.round((campaign.spend / campaign.budget) * 100)}% of ${campaign.budget.toLocaleString()} budget</p>
  </div>;
}
