"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { AlertTriangle, Save, X } from "lucide-react";
import { useCampaigns } from "@/features/ads/CampaignProvider";
import type { Campaign, CampaignStatus } from "@/features/ads/types";
import { Button } from "@/components/ui/button";
import { CampaignActivity } from "./CampaignActivity"; import { CampaignAudience } from "./CampaignAudience"; import { CampaignBudget } from "./CampaignBudget"; import { CampaignCreatives } from "./CampaignCreatives"; import { CampaignHeader } from "./CampaignHeader"; import { CampaignKeywords } from "./CampaignKeywords"; import { CampaignPerformance } from "./CampaignPerformance"; import { CampaignSettings } from "./CampaignSettings";

type EditableCampaign = Pick<Campaign, "name" | "budget" | "status" | "audience" | "keywords" | "creatives">;
const inputClass = "h-11 w-full rounded-xl border border-slate-700 bg-slate-950/60 px-3 text-sm text-white outline-none focus:border-cyan-500/60";
export function CampaignDetails({ id, initialEdit = false }: { id: string; initialEdit?: boolean }) {
  const router = useRouter(); const { campaigns, platforms, hydrated, updateCampaign, actOnCampaigns, showToast } = useCampaigns(); const campaign = campaigns.find(x => x.id === id); const [editing, setEditing] = useState(initialEdit); const [draft, setDraft] = useState<EditableCampaign | null>(() => campaign ? pickEditable(campaign) : null);
  if (!hydrated) return <CampaignDetailsSkeleton />;
  if (!campaign) return <div className="mx-auto max-w-xl rounded-3xl border border-rose-500/20 bg-rose-500/5 p-10 text-center"><AlertTriangle className="mx-auto text-rose-300" /><h1 className="mt-4 text-2xl font-semibold text-white">Campaign not found</h1><p className="mt-2 text-sm text-slate-400">This campaign does not exist or has been deleted.</p><Link href="/dashboard/ads/campaigns" className="mt-5 inline-block text-sm text-cyan-300">Return to campaigns</Link></div>;
  const editValues = draft ?? pickEditable(campaign);
  const platform = platforms.find(x => x.id === campaign.platformId)!;
  const beginEdit = () => { setDraft(pickEditable(campaign)); setEditing(true); };
  const save = () => { if (!editValues.name.trim() || editValues.budget <= 0 || !editValues.audience.trim()) return; updateCampaign(id, editValues); setEditing(false); showToast("Campaign changes saved."); };
  const lifecycle = (action: "Pause" | "Resume" | "Duplicate") => { actOnCampaigns([id], action); showToast(`${action} completed.`); };
  const archive = () => { actOnCampaigns([id], "Archive"); showToast("Campaign archived."); };
  const remove = () => { if (!window.confirm(`Delete “${campaign.name}”? This cannot be undone.`)) return; actOnCampaigns([id], "Delete"); showToast("Campaign deleted."); router.replace("/dashboard/ads/campaigns"); };
  return <div className="space-y-6 pb-8"><CampaignHeader campaign={campaign} platform={platform} onEdit={beginEdit} onAction={lifecycle} />
    {editing && <div className="rounded-3xl border border-cyan-500/30 bg-slate-900 p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold text-white">Edit campaign</h2><p className="mt-1 text-xs text-slate-500">Changes are saved to this browser only.</p></div><button onClick={() => setEditing(false)} className="text-slate-500 hover:text-white"><X size={18} /></button></div><div className="grid gap-4 sm:grid-cols-2"><EditField label="Name"><input value={editValues.name} onChange={e => setDraft({...editValues,name:e.target.value})} className={inputClass} /></EditField><EditField label="Budget"><input type="number" min="1" value={editValues.budget} onChange={e => setDraft({...editValues,budget:Number(e.target.value)})} className={inputClass} /></EditField><EditField label="Status"><select value={editValues.status} onChange={e => setDraft({...editValues,status:e.target.value as CampaignStatus})} className={inputClass}>{["Draft","Review","Scheduled","Running","Paused","Completed","Archived"].map(x => <option key={x}>{x}</option>)}</select></EditField><EditField label="Audience"><input value={editValues.audience} onChange={e => setDraft({...editValues,audience:e.target.value})} className={inputClass} /></EditField><EditField label="Keywords"><input value={editValues.keywords.join(", ")} onChange={e => setDraft({...editValues,keywords:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} className={inputClass} /></EditField><EditField label="Creative asset count"><input type="number" min="0" value={editValues.creatives} onChange={e => setDraft({...editValues,creatives:Number(e.target.value)})} className={inputClass} /></EditField></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setEditing(false)} className="border-slate-700 bg-slate-900 text-slate-300">Cancel</Button><Button onClick={save} disabled={!editValues.name.trim() || editValues.budget <= 0 || !editValues.audience.trim()} className="bg-cyan-400 text-slate-950"><Save /> Save changes</Button></div></div>}
    <nav className="sticky top-0 z-20 flex gap-5 overflow-x-auto border-y border-slate-800 bg-slate-950/90 py-3 text-xs text-slate-400 backdrop-blur-xl">{["Overview", "Performance", "Budget", "Audience", "Keywords", "Creatives", "Activity", "Settings"].map(x => <a key={x} href={`#${x.toLowerCase()}`} className="shrink-0 hover:text-cyan-300">{x}</a>)}</nav><section id="overview" className="rounded-3xl border border-slate-800 bg-gradient-to-br from-cyan-500/[0.08] to-slate-900 p-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Flight dates", `${campaign.startDate} → ${campaign.endDate}`], ["Objective", campaign.objective], ["Owner", campaign.owner], ["Audience", campaign.audience]].map(([label,value]) => <div key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-medium text-white">{value}</p></div>)}</div></section><CampaignPerformance campaign={campaign} /><div className="grid gap-6 xl:grid-cols-2"><CampaignBudget campaign={campaign} /><CampaignAudience campaign={campaign} /><CampaignKeywords campaign={campaign} /><CampaignCreatives campaign={campaign} /><CampaignActivity /><CampaignSettings onArchive={archive} onDelete={remove} /></div></div>;
}
function pickEditable(c: Campaign): EditableCampaign { return { name:c.name, budget:c.budget, status:c.status, audience:c.audience, keywords:c.keywords, creatives:c.creatives }; }
function EditField({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs text-slate-400"><span className="mb-2 block">{label}</span>{children}</label>; }
function CampaignDetailsSkeleton() { return <div className="space-y-6 animate-pulse"><div className="h-24 rounded-3xl bg-slate-900/70" /><div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-5">{Array.from({length:9},(_,i)=><div key={i} className="h-24 rounded-2xl bg-slate-900/70" />)}</div><div className="h-64 rounded-3xl bg-slate-900/70" /></div>; }
