"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, Rocket, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { platforms } from "@/features/ads/mock-data";
import { useCampaigns } from "@/features/ads/CampaignProvider";
import { createCampaignId } from "@/features/ads/campaign-utils";
import type { Campaign } from "@/features/ads/types";

const steps = ["Platform", "Objective", "Name", "Budget", "Audience", "Keywords", "Creatives", "Review", "Publish"];
const objectives = ["Conversions", "Lead generation", "Revenue", "Awareness", "Traffic", "Engagement"];
export function CampaignWizard() {
  const router = useRouter(); const { addCampaign, showToast } = useCampaigns(); const [step, setStep] = useState(0); const [errors, setErrors] = useState(""); const [uploadedCreative, setUploadedCreative] = useState(""); const [form, setForm] = useState({ platform: "google", objective: "Conversions", name: "", budget: "10000", audience: "High-intent professionals", keywords: "marketing automation, growth platform", creatives: "Product demo video, Brand image" });
  const set = (key: string, value: string) => setForm(x => ({ ...x, [key]: value }));
  const validate = () => { const message = step === 2 && !form.name.trim() ? "Campaign name is required." : step === 3 && Number(form.budget) <= 0 ? "Budget must be greater than zero." : step === 4 && !form.audience.trim() ? "Audience is required." : step === 5 && !form.keywords.trim() ? "Add at least one keyword." : step === 6 && !form.creatives.trim() ? "Add at least one creative." : ""; setErrors(message); return !message; };
  const publish = () => { const now = new Date().toISOString().slice(0, 10); const campaign: Campaign = { id: createCampaignId(), platformId: form.platform, name: form.name.trim(), objective: form.objective, budget: Number(form.budget), spend: 0, status: "Running", conversions: 0, ctr: 0, roas: 0, revenue: 0, clicks: 0, impressions: 0, cpa: 0, qualityScore: 7, owner: "Aarav Mehta", createdAt: now, startDate: now, endDate: new Date(Date.now()+90*86400000).toISOString().slice(0,10), audience: form.audience.trim(), keywords: form.keywords.split(",").map(x=>x.trim()).filter(Boolean), creatives: form.creatives.split(",").filter(x=>x.trim()).length }; addCampaign(campaign); showToast(`“${campaign.name}” created successfully.`); router.push("/dashboard/ads/campaigns"); };
  const next = () => { if (!validate()) return; setErrors(""); if (step === 8) publish(); else setStep(x => x + 1); };
  return <div className="mx-auto max-w-5xl pb-8"><Link href="/dashboard/ads/campaigns" className="inline-flex items-center gap-2 text-xs text-slate-400 hover:text-cyan-300"><ArrowLeft size={14} /> Cancel and return</Link><div className="mt-5"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Campaign builder</p><h1 className="mt-2 text-3xl font-semibold text-white">Create a new campaign</h1><p className="mt-2 text-sm text-slate-400">A guided setup across every connected advertising platform.</p></div>
    <div className="mt-7 overflow-x-auto"><div className="flex min-w-[760px] items-center">{steps.map((label,i) => <div key={label} className="flex flex-1 items-center"><div className="flex flex-col items-center gap-2"><span className={`flex h-8 w-8 items-center justify-center rounded-full border text-xs ${i < step ? "border-cyan-400 bg-cyan-400 text-slate-950" : i === step ? "border-cyan-400 bg-cyan-500/15 text-cyan-300" : "border-slate-700 text-slate-600"}`}>{i < step ? <Check size={14} /> : i+1}</span><span className={`text-[10px] ${i === step ? "text-cyan-300" : "text-slate-600"}`}>{label}</span></div>{i < steps.length-1 && <span className={`mb-5 h-px flex-1 ${i < step ? "bg-cyan-400" : "bg-slate-800"}`} />}</div>)}</div></div>
    <div className="mt-7 min-h-[390px] rounded-3xl border border-slate-800 bg-slate-900/75 p-6 sm:p-8"><div className="mb-7"><span className="text-xs text-slate-500">Step {step+1} of 9</span><h2 className="mt-1 text-xl font-semibold text-white">{["Select an advertising platform", "Choose your campaign objective", "Name your campaign", "Set your budget", "Define your audience", "Add keywords", "Upload campaign creatives", "Review your campaign", "Publish campaign"][step]}</h2></div>
      {step === 0 && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{platforms.map(p => <button key={p.id} onClick={() => set("platform", p.id)} className={`flex items-center gap-3 rounded-2xl border p-4 text-left ${form.platform === p.id ? "border-cyan-400/60 bg-cyan-500/10" : "border-slate-800 bg-slate-950/40 hover:border-slate-700"}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl font-bold" style={{ color: p.color, background: `${p.color}20` }}>{p.shortName}</span><span><span className="block text-sm font-medium text-white">{p.name}</span><span className="text-xs text-slate-500">{p.status}</span></span></button>)}</div>}
      {step === 1 && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{objectives.map(x => <button key={x} onClick={() => set("objective", x)} className={`rounded-2xl border p-5 text-left ${form.objective === x ? "border-cyan-400/60 bg-cyan-500/10 text-white" : "border-slate-800 text-slate-300 hover:border-slate-700"}`}><Sparkles size={18} className="mb-3 text-cyan-300" /><span className="font-medium">{x}</span></button>)}</div>}
      {step === 2 && <Field label="Campaign name" value={form.name} onChange={v => set("name", v)} placeholder="e.g. Q3 Enterprise Growth — Search" />}
      {step === 3 && <div className="max-w-md space-y-5"><Field label="Total campaign budget (USD)" value={form.budget} onChange={v => set("budget", v)} type="number" /><div className="rounded-2xl bg-slate-950/50 p-4 text-xs text-slate-400">Estimated daily budget: <span className="font-medium text-white">${Math.round(Number(form.budget || 0)/30).toLocaleString()}</span></div></div>}
      {step === 4 && <div className="max-w-xl space-y-4"><Field label="Audience name" value={form.audience} onChange={v => set("audience", v)} /><div className="grid grid-cols-2 gap-3">{["India, UK & US", "Ages 24–54", "English", "All devices"].map(x => <button key={x} onClick={() => set("audience", x)} className={`rounded-xl border p-3 text-left text-xs ${form.audience === x ? "border-cyan-400/60 bg-cyan-500/15 text-cyan-200" : "border-cyan-500/20 bg-cyan-500/5 text-cyan-200"}`}>✓ {x}</button>)}</div></div>}
      {step === 5 && <Field label="Keywords (comma separated)" value={form.keywords} onChange={v => set("keywords", v)} />}
      {step === 6 && <div><Field label="Creative assets" value={form.creatives} onChange={v => set("creatives", v)} /><button onClick={() => { const file = "calixo-campaign-creative.png"; setUploadedCreative(file); set("creatives", form.creatives ? `${form.creatives}, ${file}` : file); }} className="mt-4 w-full rounded-2xl border border-dashed border-slate-700 p-8 text-sm text-slate-500 hover:border-cyan-500/40 hover:text-cyan-300">Simulate creative upload</button>{uploadedCreative && <div className="mt-3 flex items-center gap-3 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-3"><div className="flex h-12 w-16 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-500/30 to-violet-500/20 text-xs text-cyan-200">PNG</div><div><p className="text-sm font-medium text-white">{uploadedCreative}</p><p className="mt-0.5 text-xs text-emerald-400">Upload complete</p></div></div>}</div>}
      {(step === 7 || step === 8) && <div className="grid gap-3 sm:grid-cols-2">{Object.entries(form).map(([key,value]) => <div key={key} className="rounded-2xl bg-slate-950/50 p-4"><p className="text-xs capitalize text-slate-500">{key}</p><p className="mt-1 text-sm font-medium text-white">{key === "platform" ? platforms.find(p => p.id === value)?.name : value || "Not provided"}</p></div>)}</div>}
    </div>{errors && <p className="mt-3 text-sm text-rose-300">{errors}</p>}<div className="mt-5 flex items-center justify-between"><Button variant="outline" disabled={step===0} onClick={() => { setErrors(""); setStep(x => x-1); }} className="border-slate-700 bg-slate-900 text-slate-300"><ChevronLeft /> Back</Button><Button onClick={next} className="bg-cyan-400 px-5 text-slate-950 hover:bg-cyan-300">{step===8 ? "Publish campaign" : "Continue"}{step===8 ? <Rocket /> : <ArrowRight />}</Button></div>
  </div>;
}
function Field({ label, value, onChange, placeholder, type="text" }: { label: string; value: string; onChange: (value:string)=>void; placeholder?: string; type?: string }) { return <label className="block max-w-xl"><span className="mb-2 block text-xs font-medium text-slate-400">{label}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-slate-700 bg-slate-950/60 px-4 text-sm text-white outline-none placeholder:text-slate-600 focus:border-cyan-500/60" /></label>; }
