"use client";
import { useState } from "react";
import { Archive, Bell, ShieldCheck, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Campaign } from "@/features/ads/types";

type SettingsModal = "alerts" | "approval" | null;
export function CampaignSettings({ campaign, onUpdate, onArchive, onDelete }: { campaign: Campaign; onUpdate: (partial: Partial<Campaign>) => void; onArchive: () => void; onDelete: () => void }) {
  const [modal, setModal] = useState<SettingsModal>(null); const [alerts, setAlerts] = useState(campaign.alertsEnabled ?? true); const [approval, setApproval] = useState(campaign.approvalRequired ?? true);
  const save = () => { onUpdate(modal === "alerts" ? { alertsEnabled: alerts } : { approvalRequired: approval }); setModal(null); };
  const cancel = () => { setAlerts(campaign.alertsEnabled ?? true); setApproval(campaign.approvalRequired ?? true); setModal(null); };
  const rows = [{ title:"Performance alerts", desc:"Notify owners when CPA changes by 20%", icon:Bell, action:()=>setModal("alerts") }, { title:"Approval workflow", desc:"Require approval before material edits", icon:ShieldCheck, action:()=>setModal("approval") }, { title:"Archive campaign", desc:"Hide from active campaign views", icon:Archive, action:onArchive }, { title:"Delete campaign", desc:"Permanently remove this campaign", icon:Trash2, action:onDelete }];
  return <section id="settings" className="rounded-3xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold text-white">Settings</h2><div className="mt-4 divide-y divide-slate-800">{rows.map(({title,desc,icon:Icon,action},i) => <button key={title} onClick={action} className={`flex w-full items-center gap-3 py-4 text-left ${i===3 ? "text-rose-300" : "text-slate-200"}`}><Icon size={17} /><span className="flex-1"><span className="block text-sm font-medium">{title}</span><span className="mt-0.5 block text-xs text-slate-500">{desc}</span></span><span className="text-slate-600">›</span></button>)}</div>
    {modal && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/75 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold text-white">{modal === "alerts" ? "Performance alerts" : "Approval workflow"}</h3><p className="mt-1 text-sm text-slate-400">{modal === "alerts" ? "Configure campaign performance notifications." : "Control whether material changes require approval."}</p></div><button onClick={cancel} className="text-slate-500 hover:text-white"><X size={18} /></button></div><label className="mt-6 flex items-center justify-between rounded-2xl bg-slate-950/50 p-4 text-sm text-slate-200"><span>{modal === "alerts" ? "Notify campaign owners" : "Require manager approval"}</span><input type="checkbox" checked={modal === "alerts" ? alerts : approval} onChange={e => modal === "alerts" ? setAlerts(e.target.checked) : setApproval(e.target.checked)} className="size-4 accent-cyan-400" /></label><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={cancel} className="border-slate-700 bg-slate-900 text-slate-300">Cancel</Button><Button onClick={save} className="bg-cyan-400 text-slate-950">Save</Button></div></div></div>}
  </section>;
}
