"use client";

import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/Card";
import { aiInsights } from "@/lib/brand-data";
import { Sparkles, Lightbulb, AlertTriangle, TrendingUp, Clock } from "lucide-react";

const typeConfig = {
  summary: { icon: Sparkles, color: 'cyan', bg: 'bg-cyan-500/10 border-cyan-500/20', text: 'text-cyan-400', label: 'Executive Summary' },
  opportunity: { icon: TrendingUp, color: 'emerald', bg: 'bg-emerald-500/10 border-emerald-500/20', text: 'text-emerald-400', label: 'Opportunity' },
  risk: { icon: AlertTriangle, color: 'red', bg: 'bg-red-500/10 border-red-500/20', text: 'text-red-400', label: 'Risk Alert' },
  recommendation: { icon: Lightbulb, color: 'amber', bg: 'bg-amber-500/10 border-amber-500/20', text: 'text-amber-400', label: 'Recommendation' },
};

export function BrandInsights() {
  return (
    <div className="space-y-6 pb-8">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}>
        <div className="flex items-center gap-3 mb-6">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-500/30 to-purple-500/30 border border-cyan-500/30">
            <Sparkles size={20} className="text-cyan-300" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white">AI-Powered Brand Intelligence</h2>
            <p className="text-sm text-slate-400">Actionable insights generated by the Calixo AI Operating System</p>
          </div>
        </div>
      </motion.div>

      <div className="grid gap-6">
        {aiInsights.map((insight, idx) => {
          const config = typeConfig[insight.type];
          const Icon = config.icon;
          return (
            <motion.div
              key={insight.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.35, delay: 0.05 * idx }}
            >
              <Card gradient className={`border-l-4 ${
                insight.type === 'summary' ? 'border-l-cyan-500' :
                insight.type === 'opportunity' ? 'border-l-emerald-500' :
                insight.type === 'risk' ? 'border-l-red-500' :
                'border-l-amber-500'
              }`}>
                <CardContent>
                  <div className="flex items-start gap-4">
                    <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${config.bg} flex-shrink-0`}>
                      <Icon size={20} className={config.text} />
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 mb-2 flex-wrap">
                        <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${config.bg} ${config.text}`}>
                          {config.label}
                        </span>
                        <span className="text-[10px] text-slate-500 flex items-center gap-1">
                          <Clock size={10} /> {new Date(insight.generatedAt).toLocaleString()}
                        </span>
                        <span className="text-[10px] text-slate-500">
                          {insight.confidence * 100}% confidence
                        </span>
                      </div>
                      <h3 className="text-base font-semibold text-white mb-2">{insight.title}</h3>
                      <p className="text-sm text-slate-300 leading-relaxed">{insight.content}</p>
                      <div className="flex items-center gap-3 mt-3">
                        {insight.relatedData.map(data => (
                          <span key={data} className="text-[10px] text-slate-500 bg-slate-800/50 px-1.5 py-0.5 rounded">
                            📊 {data}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}