"use client";
import{createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode}from"react";
import{CheckCircle2,X}from"lucide-react";
import{initialCalendarEvents}from"./mock-data";import{addDays,matchesCalendarEvent,validateCalendarEvent}from"./calendar-utils";import type{CalendarEventInput,CalendarFilterState,CalendarPostEvent,CalendarView}from"./types";
const STORAGE_KEY="calixo-social-calendar-v1";const defaultFilters:CalendarFilterState={platform:"",status:"",campaign:"",tag:"",author:"",date:""};const newId=()=>typeof crypto!=="undefined"&&"randomUUID"in crypto?crypto.randomUUID():`event-${Date.now()}`;
interface CalendarContextValue{events:CalendarPostEvent[];visibleEvents:CalendarPostEvent[];hydrated:boolean;view:CalendarView;cursorDate:Date;query:string;filters:CalendarFilterState;drawerOpen:boolean;selectedEvent:CalendarPostEvent|null;drawerStart:string;setView:(view:CalendarView)=>void;setQuery:(value:string)=>void;setFilters:(filters:CalendarFilterState)=>void;navigate:(direction:-1|0|1)=>void;openCreate:(start?:string)=>void;openEdit:(id:string)=>void;closeDrawer:()=>void;saveEvent:(input:CalendarEventInput,id?:string)=>{ok:boolean;errors:string[]};deleteEvent:(id:string)=>void;duplicateEvent:(id:string,start?:string)=>void;moveEvent:(id:string,start:string,duplicate:boolean)=>void;publishNow:(id:string)=>void;showToast:(message:string)=>void;}
const CalendarContext=createContext<CalendarContextValue|null>(null);
export function CalendarProvider({children}:{children:ReactNode}){const[events,setEvents]=useState(initialCalendarEvents);const[hydrated,setHydrated]=useState(false);const[view,setView]=useState<CalendarView>("month");const[cursorDate,setCursorDate]=useState(new Date());const[query,setQuery]=useState("");const[filters,setFilters]=useState(defaultFilters);const[drawerOpen,setDrawerOpen]=useState(false);const[selectedId,setSelectedId]=useState<string|null>(null);const[drawerStart,setDrawerStart]=useState("");const[toast,setToast]=useState("");
useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const stored=localStorage.getItem(STORAGE_KEY);if(stored)setEvents(JSON.parse(stored)as CalendarPostEvent[])}catch{localStorage.removeItem(STORAGE_KEY)}setHydrated(true)});return()=>{active=false}},[]);useEffect(()=>{if(hydrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(events))},[events,hydrated]);useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(""),3200);return()=>clearTimeout(timer)},[toast]);
const showToast=useCallback((message:string)=>setToast(message),[]);const selectedEvent=events.find(event=>event.id===selectedId)??null;const visibleEvents=useMemo(()=>events.filter(event=>matchesCalendarEvent(event,query,filters)),[events,query,filters]);
const navigate=useCallback((direction:-1|0|1)=>setCursorDate(current=>direction===0?new Date():view==="day"?addDays(current,direction):view==="week"?addDays(current,direction*7):new Date(current.getFullYear(),current.getMonth()+direction,1)),[view]);const openCreate=useCallback((start?:string)=>{setSelectedId(null);setDrawerStart(start??new Date(Date.now()+3600000).toISOString());setDrawerOpen(true)},[]);const openEdit=useCallback((id:string)=>{setSelectedId(id);setDrawerOpen(true)},[]);const closeDrawer=useCallback(()=>setDrawerOpen(false),[]);
const saveEvent=useCallback((input:CalendarEventInput,eventId?:string)=>{const errors=validateCalendarEvent(input,events,eventId);if(errors.length)return{ok:false,errors};if(eventId)setEvents(current=>current.map(event=>event.id===eventId?{...input,id:eventId}:event));else setEvents(current=>[...current,{...input,id:newId()}]);showToast(eventId?"Calendar post updated.":"Calendar post scheduled.");setDrawerOpen(false);return{ok:true,errors:[]}},[events,showToast]);
const deleteEvent=useCallback((id:string)=>{setEvents(current=>current.filter(event=>event.id!==id));setDrawerOpen(false);showToast("Calendar post deleted.")},[showToast]);const duplicateEvent=useCallback((id:string,start?:string)=>{const source=events.find(event=>event.id===id);if(!source)return;const nextStart=start??addDays(new Date(source.start),1).toISOString();const copy={...source,title:`${source.title} Copy`,start:nextStart,status:"Draft"as const};const errors=validateCalendarEvent(copy,events);if(errors.length){showToast(errors[0]);return}setEvents(current=>[...current,{...copy,id:newId()}]);showToast("Calendar post duplicated.")},[events,showToast]);
const moveEvent=useCallback((id:string,start:string,duplicate:boolean)=>{const source=events.find(event=>event.id===id);if(!source)return;const input={...source,start};const errors=validateCalendarEvent(input,events,duplicate?undefined:id);if(errors.length){showToast(errors[0]);return}if(duplicate){setEvents(current=>[...current,{...source,id:newId(),title:`${source.title} Copy`,start}]);showToast("Post duplicated to new time.")}else{setEvents(current=>current.map(event=>event.id===id?{...event,start}:event));showToast("Post rescheduled.")}},[events,showToast]);const publishNow=useCallback((id:string)=>{setEvents(current=>current.map(event=>event.id===id?{...event,status:"Published",start:new Date().toISOString()}:event));setDrawerOpen(false);showToast("Post published.")},[showToast]);
const value=useMemo(()=>({events,visibleEvents,hydrated,view,cursorDate,query,filters,drawerOpen,selectedEvent,drawerStart,setView,setQuery,setFilters,navigate,openCreate,openEdit,closeDrawer,saveEvent,deleteEvent,duplicateEvent,moveEvent,publishNow,showToast}),[events,visibleEvents,hydrated,view,cursorDate,query,filters,drawerOpen,selectedEvent,drawerStart,navigate,openCreate,openEdit,closeDrawer,saveEvent,deleteEvent,duplicateEvent,moveEvent,publishNow,showToast]);return<CalendarContext.Provider value={value}>{children}{toast&&<div role="status" className="fixed bottom-6 right-6 z-[70] flex items-center gap-3 rounded-2xl border border-emerald-500/30 bg-slate-900 px-4 py-3 text-sm text-white shadow-2xl"><CheckCircle2 size={18} className="text-emerald-400"/><span>{toast}</span><button onClick={()=>setToast("")} className="text-slate-500 hover:text-white"><X size={15}/></button></div>}</CalendarContext.Provider>}
export function useCalendar(){const context=useContext(CalendarContext);if(!context)throw new Error("useCalendar must be used within CalendarProvider");return context}
