import type { AdsRecommendation, Campaign, RecommendationStatus } from "../types";

/**
 * Recommendations are generated by threshold checks over the live campaign array on every
 * `generate()` call — replacing the 5 hand-authored strings in the legacy
 * `features/ads/mock-data.ts` (which never changed no matter what a user did to a campaign).
 */
export class AdsRecommendationRegistry {
  private statusOverrides = new Map<string, RecommendationStatus>();

  generate(campaigns: Campaign[]): AdsRecommendation[] {
    const running = campaigns.filter(c => c.status === "Running");
    if (running.length === 0) return [];

    const recommendations: AdsRecommendation[] = [];
    const avgCpa = running.reduce((sum, c) => sum + c.cpa, 0) / running.length;
    const avgRoas = running.reduce((sum, c) => sum + c.roas, 0) / running.length;
    const avgConversionRate = running.reduce((sum, c) => sum + (c.clicks > 0 ? c.conversions / c.clicks : 0), 0) / running.length;

    const nearCap = [...running].filter(c => c.budget > 0 && c.spend / c.budget >= 0.85).sort((a, b) => b.spend / b.budget - a.spend / a.budget)[0];
    if (nearCap) {
      const extra = Math.round(nearCap.budget * 0.1);
      recommendations.push({
        id: `rec-budget-${nearCap.id}`,
        title: `Increase budget for ${nearCap.name}`,
        description: `Spend has reached ${Math.round((nearCap.spend / nearCap.budget) * 100)}% of its cap. An extra $${extra.toLocaleString()} could sustain current pace without throttling delivery.`,
        impact: "High",
        category: "Budget",
        status: "new",
      });
    }

    const worstCpa = [...running].filter(c => c.cpa > avgCpa * 1.4).sort((a, b) => b.cpa - a.cpa)[0];
    if (worstCpa) {
      recommendations.push({
        id: `rec-cpa-${worstCpa.id}`,
        title: `Review ${worstCpa.name}`,
        description: `Cost per conversion is ${Math.round(((worstCpa.cpa - avgCpa) / avgCpa) * 100)}% above your account average across running campaigns.`,
        impact: "High",
        category: "Performance",
        status: "new",
      });
    }

    const bestRoas = [...running].filter(c => c.roas >= Math.max(avgRoas * 1.3, 6)).sort((a, b) => b.roas - a.roas)[0];
    if (bestRoas && bestRoas.id !== worstCpa?.id) {
      recommendations.push({
        id: `rec-winner-${bestRoas.id}`,
        title: `Duplicate ${bestRoas.name}`,
        description: `This campaign has sustained a ${bestRoas.roas.toFixed(1)}x ROAS. Test the winning structure against a fresh audience segment.`,
        impact: "High",
        category: "Performance",
        status: "new",
      });
    }

    const flaggedIds = new Set(recommendations.map(r => r.id.split("-").slice(2).join("-")));

    const staleCreative = [...running].filter(c => c.qualityScore <= 6 && !flaggedIds.has(c.id)).sort((a, b) => a.qualityScore - b.qualityScore)[0];
    if (staleCreative) {
      recommendations.push({
        id: `rec-creative-${staleCreative.id}`,
        title: `Refresh creatives for ${staleCreative.name}`,
        description: `Quality score is ${staleCreative.qualityScore}/10, among the lowest of your running campaigns — a sign of creative fatigue.`,
        impact: "Medium",
        category: "Creative",
        status: "new",
      });
    }

    const narrowAudience = [...running]
      .filter(c => c.clicks > 0 && c.conversions / c.clicks < avgConversionRate * 0.6 && !flaggedIds.has(c.id) && c.id !== staleCreative?.id)
      .sort((a, b) => a.conversions / a.clicks - b.conversions / b.clicks)[0];
    if (narrowAudience) {
      recommendations.push({
        id: `rec-audience-${narrowAudience.id}`,
        title: `Expand audience for ${narrowAudience.name}`,
        description: `Click-to-conversion rate is well below your account average, suggesting the "${narrowAudience.audience}" segment has saturated — broaden targeting to reach new qualified prospects.`,
        impact: "Medium",
        category: "Audience",
        status: "new",
      });
    }

    return recommendations.map(r => ({ ...r, status: this.statusOverrides.get(r.id) ?? r.status }));
  }

  setStatus(id: string, status: RecommendationStatus): void {
    this.statusOverrides.set(id, status);
  }

  reset(): void {
    this.statusOverrides.clear();
  }
}

export const adsRecommendationRegistry = new AdsRecommendationRegistry();
