/**
 * Calixo Platform - Internal Platform Secrets Console: Engine
 *
 * The five supported actions (Add, Update, Rotate, Validate, Test
 * Connection) all land here. Every write goes through `auditService` — the
 * brief's "every change creates an audit log entry" — tagged with the same
 * `PLATFORM_ADMIN_ORG_SENTINEL` the Internal Plan Console already uses, so
 * these events surface in the Audit Logs module's existing Platform Admin
 * Logs panel for free (`categoryFor()` there already routes anything
 * mentioning "secret" to the Security category).
 *
 * "Rotate Secret" means two different real things depending on
 * `rotationStrategy` (see types.ts): a self-issued signing secret can be
 * regenerated by Calixo itself (real Web Crypto randomness, same convention
 * as `ApiKeyService`/`SecretVault`); a vendor-issued key cannot — rotating
 * it is the same input as Update, just tagged differently for the audit
 * trail and `lastRotatedAt`.
 *
 * "Test Connection" makes a REAL, live, read-only call to the vendor's own
 * API for the 3 catalog entries where that is a standard, documented,
 * side-effect-free way to verify a credential (OpenAI `/v1/models`,
 * Anthropic `/v1/models`, Stripe `/v1/balance`) — using the admin's own
 * credential for its own sanctioned purpose, not a third-party probe.
 * Every other entry discloses "format validation only" rather than
 * fabricating a network call this environment cannot verify end-to-end
 * (no outbound egress guaranteed, no real vendor keys available to test
 * with here) — the same disclosed-placeholder posture this session has used
 * since Round 9 for connector vendor fetches.
 */
import "server-only";
import { auditService } from "@/access/audit/AuditService";
import { userRegistry } from "@/core/users";
import { PLATFORM_ADMIN_ORG_SENTINEL } from "@/features/platform-admin/commitPlanChange";
import { PROVIDER_CONFIGS } from "@/aios/config/models";
import type { AIProvider } from "@/aios/types";
import { getCatalogEntry } from "./PlatformSecretCatalog";
import { platformSecretsRegistry } from "./PlatformSecretsRegistry";
import type { PlatformSecretRecord, PlatformSecretSummary, SecretActionResult, TestOutcome } from "./types";

const AI_PROVIDER_BY_CATALOG_ID: Partial<Record<string, AIProvider>> = {
  openai_api_key: "openai",
  anthropic_api_key: "anthropic",
  google_ai_api_key: "google",
};

function actorDisplayName(userId?: string): string | undefined {
  if (!userId) return undefined;
  return userRegistry.lookup(userId)?.displayName ?? userId;
}

function toSummary(record: PlatformSecretRecord): PlatformSecretSummary {
  const entry = getCatalogEntry(record.catalogId);
  if (!entry) throw new Error(`Unknown secret catalog entry: ${record.catalogId}`);
  return {
    id: entry.id,
    section: entry.section,
    label: entry.label,
    description: entry.description,
    placeholder: entry.placeholder,
    rotationStrategy: entry.rotationStrategy,
    testSupport: entry.testSupport,
    status: record.status,
    lastUpdatedAt: record.lastUpdatedAt,
    lastUpdatedByName: actorDisplayName(record.lastUpdatedBy),
    lastRotatedAt: record.lastRotatedAt,
    lastValidatedAt: record.lastValidatedAt,
    lastValidationResult: record.lastValidationResult,
    lastValidationMessage: record.lastValidationMessage,
    lastTestedAt: record.lastTestedAt,
    lastTestResult: record.lastTestResult,
    lastTestMessage: record.lastTestMessage,
  };
}

function randomHex(bytes: number): string {
  return Array.from(globalThis.crypto.getRandomValues(new Uint8Array(bytes)))
    .map(b => b.toString(16).padStart(2, "0"))
    .join("");
}

/** Flips the real (previously never-read) `PROVIDER_CONFIGS[...].isEnabled` flag the instant an AI provider's key is configured — a concrete, verifiable "propagates immediately" effect rather than an empty claim. */
function syncAiProviderEnablement(catalogId: string, enabled: boolean): void {
  const provider = AI_PROVIDER_BY_CATALOG_ID[catalogId];
  if (provider) PROVIDER_CONFIGS[provider].isEnabled = enabled;
}

export async function listPlatformSecrets(): Promise<PlatformSecretSummary[]> {
  return (await platformSecretsRegistry.list()).map(toSummary);
}

export async function addOrUpdateSecret(catalogId: string, plaintext: string, actorId: string): Promise<SecretActionResult> {
  const entry = getCatalogEntry(catalogId);
  if (!entry) return { ok: false, error: "Unknown secret." };
  if (!plaintext.trim()) return { ok: false, error: "A value is required." };

  const existing = await platformSecretsRegistry.get(catalogId);
  const wasConfigured = existing?.status === "configured";
  if (existing?.sealedRef) platformSecretsRegistry.vault.revoke(existing.sealedRef);

  const sealedRef = await platformSecretsRegistry.vault.seal(plaintext.trim());
  const now = new Date().toISOString();
  const record: PlatformSecretRecord = {
    catalogId,
    status: "configured",
    sealedRef,
    lastUpdatedAt: now,
    lastUpdatedBy: actorId,
    lastRotatedAt: existing?.lastRotatedAt,
    lastValidatedAt: undefined,
    lastValidationResult: undefined,
    lastValidationMessage: undefined,
    lastTestedAt: undefined,
    lastTestResult: undefined,
    lastTestMessage: undefined,
  };
  await platformSecretsRegistry.set(record);
  syncAiProviderEnablement(catalogId, true);

  await auditService.recordEvent({
    organizationId: PLATFORM_ADMIN_ORG_SENTINEL,
    userId: actorId,
    eventType: wasConfigured ? "secret_updated" : "secret_added",
    resource: "platform_secret",
    resourceId: catalogId,
    description: `${actorDisplayName(actorId) ?? "Someone"} ${wasConfigured ? "updated" : "added"} the ${entry.label} secret (${entry.section})`,
  });

  return { ok: true, summary: toSummary(record) };
}

export async function rotateSecret(catalogId: string, actorId: string, plaintext?: string): Promise<SecretActionResult> {
  const entry = getCatalogEntry(catalogId);
  if (!entry) return { ok: false, error: "Unknown secret." };
  const existing = await platformSecretsRegistry.get(catalogId);
  if (!existing || existing.status !== "configured") return { ok: false, error: "Add this secret before rotating it." };

  let newPlaintext: string;
  if (entry.rotationStrategy === "generate") {
    newPlaintext = randomHex(32);
  } else {
    if (!plaintext?.trim()) return { ok: false, error: "This secret is vendor-issued — paste the new value obtained from the vendor's dashboard to rotate it." };
    newPlaintext = plaintext.trim();
  }

  if (existing.sealedRef) platformSecretsRegistry.vault.revoke(existing.sealedRef);
  const sealedRef = await platformSecretsRegistry.vault.seal(newPlaintext);
  const now = new Date().toISOString();
  const record: PlatformSecretRecord = {
    ...existing,
    sealedRef,
    lastUpdatedAt: now,
    lastUpdatedBy: actorId,
    lastRotatedAt: now,
    lastValidatedAt: undefined,
    lastValidationResult: undefined,
    lastValidationMessage: undefined,
    lastTestedAt: undefined,
    lastTestResult: undefined,
    lastTestMessage: undefined,
  };
  await platformSecretsRegistry.set(record);

  await auditService.recordEvent({
    organizationId: PLATFORM_ADMIN_ORG_SENTINEL,
    userId: actorId,
    eventType: "secret_rotated",
    resource: "platform_secret",
    resourceId: catalogId,
    description: `${actorDisplayName(actorId) ?? "Someone"} rotated the ${entry.label} secret (${entry.section})`,
  });

  return { ok: true, summary: toSummary(record) };
}

export async function validateSecret(catalogId: string, actorId: string): Promise<SecretActionResult> {
  const entry = getCatalogEntry(catalogId);
  if (!entry) return { ok: false, error: "Unknown secret." };
  const existing = await platformSecretsRegistry.get(catalogId);
  if (!existing || existing.status !== "configured" || !existing.sealedRef) return { ok: false, error: "Add this secret before validating it." };

  const plaintext = await platformSecretsRegistry.vault.reveal(existing.sealedRef);
  const { valid, message } = entry.validateFormat(plaintext);

  const now = new Date().toISOString();
  const record: PlatformSecretRecord = {
    ...existing,
    lastValidatedAt: now,
    lastValidationResult: valid ? "valid" : "invalid",
    lastValidationMessage: message,
  };
  await platformSecretsRegistry.set(record);

  await auditService.recordEvent({
    organizationId: PLATFORM_ADMIN_ORG_SENTINEL,
    userId: actorId,
    eventType: "secret_validated",
    resource: "platform_secret",
    resourceId: catalogId,
    description: `${actorDisplayName(actorId) ?? "Someone"} validated the ${entry.label} secret (${entry.section}): ${valid ? "valid" : "invalid"}`,
  });

  return { ok: true, summary: toSummary(record) };
}

interface LiveTestOutcome {
  result: TestOutcome;
  message: string;
}

async function liveFetchTest(url: string, buildHeaders: (plaintext: string) => Record<string, string>, plaintext: string): Promise<LiveTestOutcome> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000);
  try {
    const response = await fetch(url, { headers: buildHeaders(plaintext), signal: controller.signal });
    if (response.status === 200) return { result: "success", message: "Live check succeeded — the vendor accepted the credential." };
    if (response.status === 401 || response.status === 403) return { result: "failed", message: `The vendor rejected the credential (HTTP ${response.status}).` };
    return { result: "failed", message: `Unexpected response from the vendor (HTTP ${response.status}).` };
  } catch (err) {
    return { result: "unreachable", message: `Could not reach the vendor from this environment (${err instanceof Error ? err.message : "network error"}). Format was still checked locally.` };
  } finally {
    clearTimeout(timeout);
  }
}

const LIVE_TESTERS: Partial<Record<string, (plaintext: string) => Promise<LiveTestOutcome>>> = {
  openai_api_key: plaintext => liveFetchTest("https://api.openai.com/v1/models", pt => ({ Authorization: `Bearer ${pt}` }), plaintext),
  anthropic_api_key: plaintext =>
    liveFetchTest("https://api.anthropic.com/v1/models", pt => ({ "x-api-key": pt, "anthropic-version": "2023-06-01" }), plaintext),
  stripe_secret_key: plaintext => liveFetchTest("https://api.stripe.com/v1/balance", pt => ({ Authorization: `Bearer ${pt}` }), plaintext),
};

export async function testConnection(catalogId: string, actorId: string): Promise<SecretActionResult> {
  const entry = getCatalogEntry(catalogId);
  if (!entry) return { ok: false, error: "Unknown secret." };
  const existing = await platformSecretsRegistry.get(catalogId);
  if (!existing || existing.status !== "configured" || !existing.sealedRef) return { ok: false, error: "Add this secret before testing the connection." };

  const plaintext = await platformSecretsRegistry.vault.reveal(existing.sealedRef);
  const format = entry.validateFormat(plaintext);

  let result: TestOutcome;
  let message: string;

  const liveTester = entry.testSupport === "live" ? LIVE_TESTERS[catalogId] : undefined;
  if (liveTester) {
    if (!format.valid) {
      result = "failed";
      message = `Skipped the live check — ${format.message.toLowerCase()}`;
    } else {
      const live = await liveTester(plaintext);
      result = live.result;
      message = live.message;
    }
  } else {
    result = format.valid ? "format_only" : "failed";
    message = `${format.message} Live connection testing isn't wired for this provider yet — format validation only.`;
  }

  const now = new Date().toISOString();
  const record: PlatformSecretRecord = {
    ...existing,
    lastTestedAt: now,
    lastTestResult: result,
    lastTestMessage: message,
  };
  await platformSecretsRegistry.set(record);

  await auditService.recordEvent({
    organizationId: PLATFORM_ADMIN_ORG_SENTINEL,
    userId: actorId,
    eventType: "secret_connection_tested",
    resource: "platform_secret",
    resourceId: catalogId,
    description: `${actorDisplayName(actorId) ?? "Someone"} tested the connection for the ${entry.label} secret (${entry.section}): ${result}`,
  });

  return { ok: true, summary: toSummary(record) };
}
