import { Settings, UserCog, UserPlus, Building2, Link2, CreditCard, ScrollText, Webhook } from "lucide-react";
import { defineModule, type ModuleManifest } from "../ModuleManifest";

export const administrationManifest: ModuleManifest = defineModule({
  id: "administration",
  name: "Administration",
  version: "2.0.0",
  description: "Platform administration including settings, users, roles, workspaces, integrations, billing, audit logs, and API management.",
  category: "core",
  icon: Settings,
  route: "/dashboard/settings",
  subscriptionTier: "free",
  enabled: true,
  navigation: [
    {
      id: "administration",
      title: "ADMINISTRATION",
      order: 1,
      items: [
        {
          id: "settings",
          title: "Settings",
          href: "/dashboard/settings",
          icon: Settings,
          order: 0,
        },
        {
          id: "users",
          title: "Users & Teams",
          href: "/dashboard/users",
          icon: UserCog,
          order: 1,
        },
        {
          id: "roles",
          title: "Roles & Permissions",
          href: "/dashboard/roles",
          icon: UserPlus,
          order: 2,
        },
        {
          id: "workspaces",
          title: "Workspaces",
          href: "/dashboard/workspaces",
          icon: Building2,
          order: 3,
        },
        {
          id: "integrations",
          title: "Integrations",
          href: "/dashboard/integrations",
          icon: Link2,
          order: 4,
        },
        {
          id: "billing",
          title: "Billing & Plans",
          href: "/dashboard/billing",
          icon: CreditCard,
          order: 5,
        },
        {
          id: "audit",
          title: "Audit Logs",
          href: "/dashboard/audit",
          icon: ScrollText,
          order: 6,
        },
        {
          id: "api",
          title: "API & Webhooks",
          href: "/dashboard/api",
          icon: Webhook,
          order: 7,
        },
      ],
    },
  ],
  permissions: [
    { name: "settings.view", description: "View platform settings", action: "view", resource: "settings" },
    { name: "settings.manage", description: "Manage platform settings", action: "manage", resource: "settings" },
    { name: "users.view", description: "View users and teams", action: "view", resource: "users" },
    { name: "users.manage", description: "Manage users and teams", action: "manage", resource: "users" },
    { name: "roles.view", description: "View roles and permissions", action: "view", resource: "roles" },
    { name: "roles.manage", description: "Manage roles and permissions", action: "manage", resource: "roles" },
    { name: "workspaces.view", description: "View workspaces", action: "view", resource: "workspaces" },
    { name: "workspaces.manage", description: "Manage workspaces", action: "manage", resource: "workspaces" },
    { name: "integrations.view", description: "View integrations", action: "view", resource: "integrations" },
    { name: "integrations.manage", description: "Manage integrations", action: "manage", resource: "integrations" },
    { name: "billing.view", description: "View billing and plans", action: "view", resource: "billing" },
    { name: "billing.manage", description: "Manage billing and plans", action: "manage", resource: "billing" },
    { name: "audit.view", description: "View audit logs", action: "view", resource: "audit" },
    { name: "audit.export", description: "Export audit logs", action: "export", resource: "audit" },
    { name: "api.view", description: "View API keys and webhooks", action: "view", resource: "api" },
    { name: "api.manage", description: "Manage API keys and webhooks", action: "manage", resource: "api" },
  ],
  reports: [
    { id: "audit-log-report", name: "Audit Log Report", description: "Comprehensive audit activity report", format: "PDF", type: "manual" },
    { id: "user-activity", name: "User Activity Report", description: "User activity across the platform", format: "CSV", type: "scheduled" },
    { id: "billing-summary", name: "Billing Summary", description: "Monthly billing and usage summary", format: "PDF", type: "scheduled" },
  ],
  notifications: [
    { id: "billing-alert", name: "Billing Alert", description: "Alert on billing threshold or plan changes", channels: ["inApp", "email"], defaultEnabled: true },
    { id: "security-alert", name: "Security Alert", description: "Alert on suspicious activity", channels: ["inApp", "email", "slack"], defaultEnabled: true },
    { id: "integration-failure", name: "Integration Failure", description: "Alert when integration fails", channels: ["inApp", "email"], defaultEnabled: true },
  ],
  ai: { enabled: false, models: [], prompts: [] },
  settings: [
    { id: "general-settings", title: "General Settings", description: "Platform-wide configuration" },
    { id: "security-settings", title: "Security Settings", description: "Authentication and security policies" },
    { id: "notification-settings", title: "Notification Settings", description: "Global notification preferences" },
  ],
  auditLogs: [
    { action: "settings.updated", description: "Platform settings updated", logData: true },
    { action: "user.invited", description: "User invited to platform", logData: true },
    { action: "role.updated", description: "Role permissions updated", logData: true },
    { action: "integration.connected", description: "New integration connected", logData: true },
    { action: "billing.updated", description: "Billing plan updated", logData: true },
    { action: "api.key.created", description: "New API key created", logData: true },
  ],
  events: [
    { id: "user.created", name: "User Created", description: "Fired when a new user is created" },
    { id: "user.deactivated", name: "User Deactivated", description: "Fired when a user is deactivated" },
    { id: "workspace.created", name: "Workspace Created", description: "Fired when a new workspace is created" },
  ],
  metadata: { order: 8 },
});