"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { composerPlatforms } from "./composer-config";
import type { AiAction, ComposerDraft, ComposerPlatform } from "./composer-types";

const CURRENT_KEY="calixo-social-composer-current-v1"; const DRAFTS_KEY="calixo-social-composer-drafts-v1";
const id=()=>typeof crypto!=="undefined"&&"randomUUID"in crypto?crypto.randomUUID():`draft-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const blankDraft=():ComposerDraft=>({id:id(),title:"Untitled social post",platforms:[],content:"",media:[],audience:"Public",customAudience:"",publishingMode:"now",scheduledDate:new Date(Date.now()+86400000).toISOString().slice(0,10),scheduledTime:"10:00",timezone:"Asia/Kolkata",recurring:false,recurringFrequency:"Weekly",previewPlatform:"Facebook",updatedAt:new Date().toISOString()});
const readFile=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});

export function usePostComposer(){
  const[draft,setDraft]=useState<ComposerDraft>(blankDraft);const[savedDrafts,setSavedDrafts]=useState<ComposerDraft[]>([]);const[hydrated,setHydrated]=useState(false);const[aiBusy,setAiBusy]=useState(false);
  useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const current=localStorage.getItem(CURRENT_KEY);const saved=localStorage.getItem(DRAFTS_KEY);if(current)setDraft(JSON.parse(current)as ComposerDraft);if(saved)setSavedDrafts(JSON.parse(saved)as ComposerDraft[])}catch{localStorage.removeItem(CURRENT_KEY);localStorage.removeItem(DRAFTS_KEY)}setHydrated(true)});return()=>{active=false}},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem(CURRENT_KEY,JSON.stringify({...draft,updatedAt:new Date().toISOString()}))},[draft,hydrated]);
  useEffect(()=>{if(hydrated)localStorage.setItem(DRAFTS_KEY,JSON.stringify(savedDrafts))},[savedDrafts,hydrated]);
  const update=useCallback(<K extends keyof ComposerDraft>(key:K,value:ComposerDraft[K])=>setDraft(current=>({...current,[key]:value})),[]);
  const togglePlatform=useCallback((platform:ComposerPlatform)=>setDraft(current=>{const selected=current.platforms.includes(platform)?current.platforms.filter(item=>item!==platform):[...current.platforms,platform];return{...current,platforms:selected,previewPlatform:selected.includes(current.previewPlatform)?current.previewPlatform:selected[0]??"Facebook"}}),[]);
  const addMedia=useCallback(async(files:File[])=>{const media=await Promise.all(files.map(async file=>({id:id(),name:file.name,type:file.type.startsWith("video")?"video"as const:"image"as const,dataUrl:await readFile(file)})));setDraft(current=>({...current,media:[...current.media,...media]}))},[]);
  /** Attaches a real asset from the Content Studio Asset Library (via `assetsPlatformAPI`) alongside local file upload — Social Media owns no asset storage of its own. */
  const addMediaFromAssets=useCallback((assets:{id:string;name:string;type:"image"|"video";url:string}[])=>{const media=assets.map(asset=>({id:id(),name:asset.name,type:asset.type,dataUrl:asset.url}));setDraft(current=>({...current,media:[...current.media,...media]}))},[]);
  const removeMedia=useCallback((mediaId:string)=>setDraft(current=>({...current,media:current.media.filter(item=>item.id!==mediaId)})),[]);
  const moveMedia=useCallback((mediaId:string,direction:-1|1)=>setDraft(current=>{const index=current.media.findIndex(item=>item.id===mediaId);const target=index+direction;if(index<0||target<0||target>=current.media.length)return current;const media=[...current.media];[media[index],media[target]]=[media[target],media[index]];return{...current,media}}),[]);
  const validationMessages=useMemo(()=>{const messages:string[]=[];if(!draft.platforms.length)messages.push("Select at least one platform.");if(!draft.content.trim())messages.push("Enter post content.");const mediaPlatforms=draft.platforms.filter(platform=>composerPlatforms.find(item=>item.name===platform)?.requiresMedia);if(mediaPlatforms.length&&!draft.media.length)messages.push(`Add media for ${mediaPlatforms.join(", ")}.`);const exceeded=draft.platforms.filter(platform=>draft.content.length>(composerPlatforms.find(item=>item.name===platform)?.limit??Infinity));if(exceeded.length)messages.push(`Character limit exceeded for ${exceeded.join(", ")}.`);if(draft.publishingMode==="schedule"&&(!draft.scheduledDate||!draft.scheduledTime))messages.push("Choose a schedule date and time.");if(draft.audience==="Custom Audience"&&!draft.customAudience.trim())messages.push("Enter a custom audience.");return messages},[draft]);
  const canPublish=validationMessages.length===0;
  const saveDraft=useCallback(()=>{const saved={...draft,title:draft.content.trim().slice(0,48)||draft.title,updatedAt:new Date().toISOString()};setSavedDrafts(current=>[saved,...current.filter(item=>item.id!==saved.id)]);return saved},[draft]);
  const loadDraft=useCallback((item:ComposerDraft)=>setDraft({...item}),[]);
  const deleteDraft=useCallback((draftId:string)=>setSavedDrafts(current=>current.filter(item=>item.id!==draftId)),[]);
  const duplicateDraft=useCallback((item:ComposerDraft)=>{const copy={...item,id:id(),title:`${item.title} Copy`,updatedAt:new Date().toISOString()};setSavedDrafts(current=>[copy,...current]);setDraft(copy)},[]);
  const discard=useCallback(()=>{const fresh=blankDraft();setDraft(fresh);localStorage.removeItem(CURRENT_KEY)},[]);
  const runAi=useCallback((action:AiAction)=>{setAiBusy(true);window.setTimeout(()=>{setDraft(current=>{const base=current.content.trim()||"Build stronger customer relationships with one connected social workspace.";const outputs:Record<AiAction,string>={generate:"Turn every social signal into a smarter next move with Calixo — one workspace for content, community, and growth. ✨",rewrite:`${base.replace(/\.$/,"")} — reimagined for clearer, more engaging social storytelling.`,professional:`A connected social strategy enables teams to translate audience insight into measurable, sustainable growth.`,friendly:`Good social media should feel less like busywork and more like a great conversation. Calixo helps make that happen. 👋`,promotional:`Ready to transform your social workflow? Plan, publish, and grow faster with Calixo. Start today.`,shorten:base.split(" ").slice(0,Math.max(8,Math.ceil(base.split(" ").length/2))).join(" "),expand:`${base} Bring planning, publishing, analytics, and community insight together so every post learns from the last and contributes to what comes next.`,grammar:base.charAt(0).toUpperCase()+base.slice(1).replace(/\s+/g," ").replace(/([^.!?])$/,"$1."),hashtags:`${base}\n\n#SocialMedia #MarketingAI #ContentStrategy #Calixo`,cta:`${base}\n\nExplore the Calixo workspace and start building your next campaign today.`,translate:`[Spanish] ${base} — Conecta tu estrategia social y convierte cada interacción en crecimiento.`,summarize:base.split(/[.!?]/)[0]+"."};return{...current,content:outputs[action]}});setAiBusy(false)},450)},[]);
  return{draft,savedDrafts,hydrated,aiBusy,update,togglePlatform,addMedia,addMediaFromAssets,removeMedia,moveMedia,validationMessages,canPublish,saveDraft,loadDraft,deleteDraft,duplicateDraft,discard,runAi};
}
