import type { RecommendationStatus, SocialAccount, SocialPost, SocialRecommendation } from "../types";

/**
 * Recommendations are generated by threshold checks over the live account/post arrays on every
 * `generate()` call — replacing the 4 hand-authored strings in the legacy
 * `features/social/mock-data.ts` (which never changed no matter what a user did to an account).
 */
export class SocialRecommendationRegistry {
  private statusOverrides = new Map<string, RecommendationStatus>();

  generate(accounts: SocialAccount[], posts: SocialPost[]): SocialRecommendation[] {
    const recommendations: SocialRecommendation[] = [];
    const connected = accounts.filter(a => a.status === "Connected");
    const avgEngagement = connected.length > 0 ? connected.reduce((sum, a) => sum + a.engagementRate, 0) / connected.length : 0;

    const disconnected = accounts.find(a => a.status !== "Connected");
    if (disconnected) {
      recommendations.push({
        id: `rec-reconnect-${disconnected.id}`,
        title: `Reconnect ${disconnected.platform}`,
        description: `${disconnected.platform} is ${disconnected.status.toLowerCase()} — restore the connection to resume publishing and performance tracking.`,
        impact: "Medium",
        category: "Growth",
        status: "new",
      });
    }

    const topEngagement = [...connected].sort((a, b) => b.engagementRate - a.engagementRate)[0];
    if (topEngagement) {
      recommendations.push({
        id: `rec-timing-${topEngagement.id}`,
        title: `Post on ${topEngagement.platform} during peak engagement`,
        description: `${topEngagement.platform} has your highest engagement rate at ${topEngagement.engagementRate.toFixed(1)}% — prioritize your best content there this week.`,
        impact: "High",
        category: "Timing",
        status: "new",
      });
    }

    const draftPosts = posts.filter(p => p.status === "Draft");
    if (draftPosts.length > 0) {
      recommendations.push({
        id: "rec-drafts-pending",
        title: `Publish or schedule ${draftPosts.length} pending draft${draftPosts.length === 1 ? "" : "s"}`,
        description: "These drafts have been sitting without a publish or schedule date.",
        impact: draftPosts.length >= 3 ? "High" : "Medium",
        category: "Content",
        status: "new",
      });
    }

    const lowEngagement = [...connected].filter(a => a.engagementRate < avgEngagement * 0.7 && a.id !== topEngagement?.id).sort((a, b) => a.engagementRate - b.engagementRate)[0];
    if (lowEngagement) {
      recommendations.push({
        id: `rec-engagement-${lowEngagement.id}`,
        title: `Boost engagement on ${lowEngagement.platform}`,
        description: `${lowEngagement.platform}'s engagement rate (${lowEngagement.engagementRate.toFixed(1)}%) trails your account average of ${avgEngagement.toFixed(1)}% — consider more interactive formats.`,
        impact: "Medium",
        category: "Engagement",
        status: "new",
      });
    }

    return recommendations.map(r => ({ ...r, status: this.statusOverrides.get(r.id) ?? r.status }));
  }

  setStatus(id: string, status: RecommendationStatus): void {
    this.statusOverrides.set(id, status);
  }

  reset(): void {
    this.statusOverrides.clear();
  }
}

export const socialRecommendationRegistry = new SocialRecommendationRegistry();
