/**
 * Calixo Platform — Creative Type Service
 *
 * Defines every supported creative type with layout rules,
 * structure, visual hierarchy, and required elements.
 */

import type { CreativeType, CreativeTypeKnowledge, LayoutSection } from "./types";

const CREATIVE_TYPES: Record<CreativeType, CreativeTypeKnowledge> = {
  "social-post": {
    type: "social-post", displayName: "Social Post",
    description: "Standard single-image or video social media post",
    compatiblePlatforms: ["facebook", "instagram", "linkedin", "x"],
    layoutRules: ["Visual-first, text as support", "One clear message per creative", "Brand element subtle but present"],
    recommendedStructure: [
      { name: "Background", position: "full", elements: [{ type: "background", label: "Background image/gradient", position: { x: "0", y: "0", width: "100%", height: "100%" }, required: true, style: "High-quality visual" }], notes: "Hero visual takes 70-80% of canvas" },
      { name: "Text Overlay", position: "bottom third", elements: [{ type: "headline", label: "Primary headline", position: { x: "5%", y: "65%", width: "90%", height: "auto" }, required: true, style: "Bold, high contrast" }, { type: "text", label: "Supporting text", position: { x: "5%", y: "80%", width: "90%", height: "auto" }, required: false, style: "Smaller, lighter weight" }], notes: "Keep text minimal" },
      { name: "Brand", position: "top", elements: [{ type: "logo", label: "Brand logo", position: { x: "5%", y: "3%", width: "15%", height: "auto" }, required: false, style: "Subtle, small" }], notes: "Optional on social posts" },
    ],
    visualHierarchy: ["Hero visual", "Headline", "Supporting text", "Brand logo"],
    requiredElements: ["Hero visual", "Headline"],
    optionalElements: ["Supporting text", "Brand logo", "CTA button"],
  },
  "story": {
    type: "story", displayName: "Story",
    description: "Full-screen vertical story format (Instagram, Facebook, WhatsApp)",
    compatiblePlatforms: ["instagram", "facebook", "meta-ads", "whatsapp"],
    layoutRules: ["Full-screen vertical 9:16", "Safe areas: avoid top/bottom 150px for UI elements", "Interactive elements: polls, swipe-up, stickers in overlay zone"],
    recommendedStructure: [
      { name: "Background", position: "full", elements: [{ type: "background", label: "Full-screen image/video", position: { x: "0", y: "0", width: "100%", height: "100%" }, required: true, style: "9:16 vertical" }], notes: "Must fill entire 1080x1920 canvas" },
      { name: "Content", position: "center safe zone", elements: [{ type: "headline", label: "Key message", position: { x: "10%", y: "35%", width: "80%", height: "auto" }, required: true, style: "Large, bold" }, { type: "cta", label: "Swipe-up / Link sticker zone", position: { x: "20%", y: "80%", width: "60%", height: "auto" }, required: false, style: "CTA indicator" }], notes: "Keep content in centre safe zone" },
      { name: "Brand", position: "top", elements: [{ type: "logo", label: "Brand logo", position: { x: "5%", y: "5%", width: "20%", height: "auto" }, required: true, style: "Visible but not dominant" }], notes: "Top position avoids UI overlap" },
    ],
    visualHierarchy: ["Background visual", "Key message", "CTA indicator", "Brand logo"],
    requiredElements: ["Background visual", "Key message", "Brand logo"],
    optionalElements: ["CTA indicator", "Poll sticker zone"],
  },
  "carousel": {
    type: "carousel", displayName: "Carousel",
    description: "Multi-slide swipeable carousel (2-10 slides)",
    compatiblePlatforms: ["instagram", "facebook", "linkedin", "meta-ads"],
    layoutRules: ["Consistent design language across all slides", "First slide is the hook — strongest visual", "Last slide should have CTA", "Each slide tells one part of the story"],
    recommendedStructure: [
      { name: "Slide 1 - Hook", position: "card 1", elements: [{ type: "headline", label: "Hook headline", position: { x: "10%", y: "20%", width: "80%", height: "auto" }, required: true, style: "Bold, provocative" }, { type: "image", label: "Hero image", position: { x: "0", y: "45%", width: "100%", height: "55%" }, required: true, style: "Strong visual" }], notes: "Grab attention immediately" },
      { name: "Slide 2-N - Content", position: "cards 2...N-1", elements: [{ type: "headline", label: "Content headline", position: { x: "5%", y: "5%", width: "90%", height: "auto" }, required: true, style: "Informative" }, { type: "text", label: "Content body", position: { x: "5%", y: "20%", width: "90%", height: "60%" }, required: true, style: "Readable" }, { type: "image", label: "Supporting visual", position: { x: "20%", y: "70%", width: "60%", height: "30%" }, required: false, style: "Complementary" }], notes: "Deliver value" },
      { name: "Slide N - CTA", position: "last card", elements: [{ type: "headline", label: "CTA headline", position: { x: "10%", y: "30%", width: "80%", height: "auto" }, required: true, style: "Action-oriented" }, { type: "cta", label: "CTA button", position: { x: "25%", y: "55%", width: "50%", height: "auto" }, required: true, style: "Prominent" }, { type: "logo", label: "Brand logo", position: { x: "40%", y: "85%", width: "20%", height: "auto" }, required: true, style: "Centred" }], notes: "Drive action" },
    ],
    visualHierarchy: ["Hook (slide 1)", "Content slides", "CTA slide", "Consistent branding throughout"],
    requiredElements: ["Hook slide", "Content slides", "CTA slide", "Brand logo"],
    optionalElements: ["Slide numbers", "Progress indicator"],
  },
  "reel-cover": { type: "reel-cover", displayName: "Reel Cover", description: "Cover image for Instagram Reels", compatiblePlatforms: ["instagram"], layoutRules: ["9:16 vertical", "Centre focal point", "Text must not overlap with UI elements"], recommendedStructure: [{ name: "Background", position: "full", elements: [{ type: "background", label: "Reel cover image", position: { x: "0", y: "0", width: "100%", height: "100%" }, required: true, style: "Bold, eye-catching thumbnail" }], notes: "Must work as a thumbnail" }, { name: "Text", position: "centre", elements: [{ type: "headline", label: "Title text", position: { x: "10%", y: "40%", width: "80%", height: "auto" }, required: true, style: "Large, bold, high contrast" }], notes: "Keep text under 5 words" }], visualHierarchy: ["Cover image", "Title text"], requiredElements: ["Cover image", "Title text"], optionalElements: ["Brand logo"] },
  "thumbnail": { type: "thumbnail", displayName: "Thumbnail", description: "YouTube/video thumbnail", compatiblePlatforms: ["youtube"], layoutRules: ["16:9 landscape", "High contrast", "Clear focal point", "Faces with expressions perform best"], recommendedStructure: [{ name: "Background", position: "full", elements: [{ type: "background", label: "Thumbnail image", position: { x: "0", y: "0", width: "100%", height: "100%" }, required: true, style: "High contrast, dramatic" }], notes: "Eye-catching at small sizes" }, { name: "Text", position: "varies", elements: [{ type: "headline", label: "Title text", position: { x: "5%", y: "10%", width: "90%", height: "auto" }, required: true, style: "Under 6 words, bold, outlined" }], notes: "Avoid bottom-right (timestamp zone)" }, { name: "Brand", position: "top", elements: [{ type: "logo", label: "Channel branding", position: { x: "5%", y: "5%", width: "10%", height: "auto" }, required: false, style: "Small, corner" }], notes: "Consistent placement builds recognition" }], visualHierarchy: ["Thumbnail image", "Title text", "Channel branding"], requiredElements: ["Thumbnail image", "Title text"], optionalElements: ["Channel branding", "Face/reaction element"] },
  "display-banner": { type: "display-banner", displayName: "Display Banner", description: "Standard display advertising banner", compatiblePlatforms: ["google-display", "performance-max", "meta-ads"], layoutRules: ["Multiple sizes required (responsive)", "Text under 20% of image", "Clear CTA", "Brand visible"], recommendedStructure: [{ name: "Background", position: "full", elements: [{ type: "background", label: "Banner image", position: { x: "0", y: "0", width: "100%", height: "100%" }, required: true, style: "Clean, uncluttered" }], notes: "Adapts to multiple sizes" }, { name: "Content", position: "left/center", elements: [{ type: "headline", label: "Headline", position: { x: "8%", y: "15%", width: "60%", height: "auto" }, required: true, style: "Bold" }, { type: "text", label: "Body copy", position: { x: "8%", y: "50%", width: "60%", height: "auto" }, required: false, style: "Concise" }, { type: "cta", label: "CTA button", position: { x: "70%", y: "70%", width: "25%", height: "auto" }, required: true, style: "High contrast button" }], notes: "Clear visual flow" }, { name: "Brand", position: "top", elements: [{ type: "logo", label: "Brand logo", position: { x: "5%", y: "5%", width: "15%", height: "auto" }, required: true, style: "Small, top corner" }], notes: "" }], visualHierarchy: ["Brand logo (subtle)", "Headline", "Body copy", "CTA button"], requiredElements: ["Banner image", "Headline", "CTA button", "Brand logo"], optionalElements: ["Body copy"] },
  "poster": { type: "poster", displayName: "Poster", description: "Print/digital poster for events or promotions", compatiblePlatforms: ["print"], layoutRules: ["Visual hierarchy: Headline → Visual → Details → CTA", "Readable from 2-3m distance", "Include bleed area for print"], recommendedStructure: [{ name: "Header", position: "top", elements: [{ type: "headline", label: "Main headline", position: { x: "10%", y: "5%", width: "80%", height: "20%" }, required: true, style: "Large, bold, eye-catching" }], notes: "Most prominent element" }, { name: "Hero", position: "center", elements: [{ type: "image", label: "Hero visual", position: { x: "5%", y: "25%", width: "90%", height: "50%" }, required: true, style: "High resolution, impactful" }], notes: "Main visual focus" }, { name: "Details", position: "bottom", elements: [{ type: "text", label: "Date, time, location", position: { x: "10%", y: "75%", width: "80%", height: "15%" }, required: true, style: "Clear, readable" }, { type: "cta", label: "CTA / QR code", position: { x: "60%", y: "85%", width: "30%", height: "10%" }, required: true, style: "Scannable QR or URL" }], notes: "Essential info" }, { name: "Brand", position: "top", elements: [{ type: "logo", label: "Brand/event logo", position: { x: "5%", y: "5%", width: "15%", height: "auto" }, required: true, style: "Prominent" }], notes: "" }], visualHierarchy: ["Headline", "Hero visual", "Event details", "CTA/QR code", "Brand logo"], requiredElements: ["Headline", "Hero visual", "Event details", "CTA/QR"], optionalElements: ["Sponsor logos"] },
  "flyer": { type: "flyer", displayName: "Flyer", description: "Promotional flyer (A5/A6/DL)", compatiblePlatforms: ["print"], layoutRules: ["Front: Strong visual + headline", "Back: Details + CTA", "Keep it scannable"], recommendedStructure: [{ name: "Front - Hero", position: "front cover", elements: [{ type: "headline", label: "Offer headline", position: { x: "10%", y: "10%", width: "80%", height: "auto" }, required: true, style: "Bold, promotional" }, { type: "image", label: "Product/offer visual", position: { x: "10%", y: "35%", width: "80%", height: "50%" }, required: true, style: "High quality" }], notes: "Immediate impact" }, { name: "Front - CTA", position: "front bottom", elements: [{ type: "cta", label: "CTA / Offer", position: { x: "20%", y: "88%", width: "60%", height: "auto" }, required: true, style: "Urgent" }], notes: "Clear action" }, { name: "Back", position: "back cover", elements: [{ type: "text", label: "Details/contact", position: { x: "10%", y: "10%", width: "80%", height: "70%" }, required: true, style: "Body text" }, { type: "logo", label: "Brand logo", position: { x: "30%", y: "85%", width: "40%", height: "auto" }, required: true, style: "Centred" }], notes: "Supporting info" }], visualHierarchy: ["Headline", "Visual", "CTA", "Details (back)"], requiredElements: ["Headline", "Visual", "CTA", "Details"], optionalElements: ["Tear-off tabs"] },
  "brochure": { type: "brochure", displayName: "Brochure", description: "Tri-fold or bi-fold brochure", compatiblePlatforms: ["print"], layoutRules: ["Front panel: Strong visual + headline", "Inside: Detailed info", "Back panel: Contact + CTA", "Consistent branding across all panels"], recommendedStructure: [{ name: "Front Panel", position: "cover", elements: [{ type: "headline", label: "Main headline", position: { x: "10%", y: "15%", width: "80%", height: "auto" }, required: true, style: "Large, engaging" }, { type: "image", label: "Cover image", position: { x: "5%", y: "45%", width: "90%", height: "45%" }, required: true, style: "Professional" }], notes: "First impression" }, { name: "Inside Panels", position: "inside spread", elements: [{ type: "headline", label: "Section headlines", position: { x: "5%", y: "5%", width: "90%", height: "auto" }, required: true, style: "Informative" }, { type: "text", label: "Body content", position: { x: "5%", y: "15%", width: "90%", height: "70%" }, required: true, style: "Readable columns" }, { type: "image", label: "Supporting images", position: { x: "5%", y: "70%", width: "40%", height: "25%" }, required: false, style: "Illustrative" }], notes: "Value content" }, { name: "Back Panel", position: "back cover", elements: [{ type: "text", label: "Contact info", position: { x: "10%", y: "10%", width: "80%", height: "50%" }, required: true, style: "Clear" }, { type: "cta", label: "CTA / QR", position: { x: "20%", y: "65%", width: "60%", height: "auto" }, required: true, style: "Actionable" }, { type: "logo", label: "Brand logo", position: { x: "30%", y: "85%", width: "40%", height: "auto" }, required: true, style: "Centred" }], notes: "Contact + CTA" }], visualHierarchy: ["Front panel", "Inside panels", "Back panel"], requiredElements: ["Headline", "Cover image", "Body content", "Contact info", "Brand logo"], optionalElements: ["Charts/graphs"] },
  "standee": { type: "standee", displayName: "Standee", description: "Roll-up banner / standee (850x2000mm)", compatiblePlatforms: ["print"], layoutRules: ["Vertical orientation (tall, narrow)", "Readable from 2-3m", "Maximum 3 lines of text", "Logo at top, CTA at bottom"], recommendedStructure: [{ name: "Header", position: "top", elements: [{ type: "logo", label: "Brand logo", position: { x: "20%", y: "3%", width: "60%", height: "10%" }, required: true, style: "Large, centred" }], notes: "Eye level" }, { name: "Hero", position: "center", elements: [{ type: "image", label: "Hero visual", position: { x: "10%", y: "18%", width: "80%", height: "55%" }, required: true, style: "High resolution, 150+ DPI" }], notes: "Main focal point" }, { name: "Message", position: "lower center", elements: [{ type: "headline", label: "Key message", position: { x: "10%", y: "75%", width: "80%", height: "auto" }, required: true, style: "Bold, 3 lines max" }], notes: "Concise" }, { name: "Footer", position: "bottom", elements: [{ type: "cta", label: "CTA / QR", position: { x: "20%", y: "88%", width: "60%", height: "auto" }, required: true, style: "Clear, scannable" }], notes: "Action at bottom" }], visualHierarchy: ["Brand logo", "Hero visual", "Key message", "CTA/QR"], requiredElements: ["Brand logo", "Hero visual", "Key message", "CTA/QR"], optionalElements: [] },
  "billboard": { type: "billboard", displayName: "Billboard", description: "Large-format outdoor billboard", compatiblePlatforms: ["print"], layoutRules: ["Readable from 50m+ distance", "7 words maximum total", "Single, powerful image", "High contrast essential"], recommendedStructure: [{ name: "Background", position: "full", elements: [{ type: "background", label: "Billboard image", position: { x: "0", y: "0", width: "100%", height: "100%" }, required: true, style: "Bold, high contrast" }], notes: "Must dominate" }, { name: "Message", position: "center", elements: [{ type: "headline", label: "Headline (5-7 words)", position: { x: "5%", y: "30%", width: "90%", height: "auto" }, required: true, style: "Ultra-bold, massive" }], notes: "Under 7 words" }, { name: "Brand", position: "bottom", elements: [{ type: "logo", label: "Brand logo", position: { x: "35%", y: "85%", width: "30%", height: "auto" }, required: true, style: "Large, readable" }, { type: "cta", label: "URL/phone", position: { x: "30%", y: "92%", width: "40%", height: "auto" }, required: false, style: "Simple URL" }], notes: "Contact at bottom" }], visualHierarchy: ["Background image", "Headline (7 words max)", "Brand logo", "URL/phone"], requiredElements: ["Background image", "Headline", "Brand logo"], optionalElements: ["URL", "Phone number"] },
  "presentation": { type: "presentation", displayName: "Presentation", description: "Slide presentation (16:9)", compatiblePlatforms: ["blog", "linkedin", "print"], layoutRules: ["Consistent template", "One idea per slide", "Visual + minimal text", "16:9 landscape"], recommendedStructure: [{ name: "Title", position: "top", elements: [{ type: "headline", label: "Slide title", position: { x: "8%", y: "5%", width: "84%", height: "auto" }, required: true, style: "Bold" }], notes: "Clear title" }, { name: "Content", position: "center", elements: [{ type: "image", label: "Visual/chart", position: { x: "5%", y: "25%", width: "55%", height: "65%" }, required: true, style: "Data viz or image" }, { type: "text", label: "Bullet points", position: { x: "65%", y: "25%", width: "30%", height: "65%" }, required: true, style: "3-5 bullet points max" }], notes: "Visual + bullets" }, { name: "Footer", position: "bottom", elements: [{ type: "logo", label: "Brand logo", position: { x: "5%", y: "92%", width: "8%", height: "auto" }, required: true, style: "Small" }], notes: "Consistent footer" }], visualHierarchy: ["Slide title", "Visual/chart", "Bullet points", "Footer branding"], requiredElements: ["Slide title", "Visual/chart", "Bullet points", "Brand logo"], optionalElements: ["Slide number"] },
  "infographic": { type: "infographic", displayName: "Infographic", description: "Data visualization infographic", compatiblePlatforms: ["blog", "linkedin", "facebook", "instagram"], layoutRules: ["Vertical flow (top to bottom)", "Data-driven visuals", "Consistent colour coding", "Clear section breaks"], recommendedStructure: [{ name: "Header", position: "top", elements: [{ type: "headline", label: "Infographic title", position: { x: "5%", y: "3%", width: "90%", height: "auto" }, required: true, style: "Large, bold" }, { type: "text", label: "Subtitle", position: { x: "5%", y: "10%", width: "90%", height: "auto" }, required: false, style: "Supporting" }], notes: "Title area" }, { name: "Sections", position: "body flow", elements: [{ type: "image", label: "Data visualizations", position: { x: "5%", y: "20%", width: "90%", height: "60%" }, required: true, style: "Charts, icons, illustrations" }, { type: "text", label: "Data labels", position: { x: "5%", y: "80%", width: "90%", height: "auto" }, required: true, style: "Clear labels" }], notes: "Data story flow" }, { name: "Footer", position: "bottom", elements: [{ type: "logo", label: "Brand logo", position: { x: "5%", y: "95%", width: "10%", height: "auto" }, required: true, style: "Small" }, { type: "text", label: "Source/reference", position: { x: "20%", y: "95%", width: "75%", height: "auto" }, required: false, style: "Tiny text" }], notes: "Sources and brand" }], visualHierarchy: ["Title", "Data visualizations", "Labels", "Footer"], requiredElements: ["Title", "Data visualizations", "Labels", "Brand logo"], optionalElements: ["Subtitle", "Source references"] },
  "email-header": { type: "email-header", displayName: "Email Header", description: "Email newsletter/marketing header", compatiblePlatforms: ["email"], layoutRules: ["600px max width", "Above-fold content priority", "Web-safe fonts", "Mobile responsive"], recommendedStructure: [{ name: "Header", position: "top", elements: [{ type: "logo", label: "Brand logo", position: { x: "center", y: "5%", width: "30%", height: "auto" }, required: true, style: "Centred, clean" }], notes: "Email branding" }, { name: "Hero", position: "below logo", elements: [{ type: "image", label: "Header image", position: { x: "0", y: "15%", width: "100%", height: "50%" }, required: true, style: "600px wide, engaging" }, { type: "headline", label: "Headline", position: { x: "10%", y: "70%", width: "80%", height: "auto" }, required: true, style: "Bold, 24-30px" }, { type: "cta", label: "CTA button", position: { x: "center", y: "82%", width: "40%", height: "auto" }, required: true, style: "44px+ touch target" }], notes: "Above-fold content" }], visualHierarchy: ["Brand logo", "Header image", "Headline", "CTA button"], requiredElements: ["Brand logo", "Header image", "Headline", "CTA button"], optionalElements: ["Preview text"] },
  "landing-hero": { type: "landing-hero", displayName: "Landing Page Hero", description: "Landing page hero section", compatiblePlatforms: ["blog", "email"], layoutRules: ["1200x800px standard", "Headline + subheadline + CTA + hero image", "Above-fold", "Single CTA focus"], recommendedStructure: [{ name: "Hero", position: "full width", elements: [{ type: "background", label: "Hero background", position: { x: "0", y: "0", width: "100%", height: "100%" }, required: true, style: "1200x800, impactful" }], notes: "Full-width visual" }, { name: "Content", position: "left/center overlay", elements: [{ type: "headline", label: "Main headline", position: { x: "8%", y: "25%", width: "50%", height: "auto" }, required: true, style: "Bold, benefit-driven" }, { type: "text", label: "Subheadline", position: { x: "8%", y: "45%", width: "50%", height: "auto" }, required: true, style: "Supporting value prop" }, { type: "cta", label: "CTA button", position: { x: "8%", y: "65%", width: "25%", height: "auto" }, required: true, style: "High contrast, prominent" }], notes: "Left-aligned text overlay" }, { name: "Brand", position: "top", elements: [{ type: "logo", label: "Brand logo", position: { x: "5%", y: "5%", width: "12%", height: "auto" }, required: true, style: "Navigation bar area" }], notes: "Top-left logo" }], visualHierarchy: ["Main headline", "Subheadline", "CTA button", "Hero image", "Brand logo"], requiredElements: ["Main headline", "Subheadline", "CTA button", "Hero image", "Brand logo"], optionalElements: ["Trust indicators", "Stats"] },
};

export const CreativeTypeService = {
  get(type: CreativeType): CreativeTypeKnowledge {
    return { ...CREATIVE_TYPES[type] };
  },
  getAll(): CreativeTypeKnowledge[] {
    return Object.values(CREATIVE_TYPES).map(t => ({ ...t }));
  },
  getLayout(type: CreativeType): LayoutSection[] {
    return CREATIVE_TYPES[type].recommendedStructure.map(s => ({ ...s, elements: s.elements.map(e => ({ ...e, position: { ...e.position } })) }));
  },
  getForPlatform(platform: string): CreativeTypeKnowledge[] {
    return this.getAll().filter(t => t.compatiblePlatforms.includes(platform as never));
  },
  getAllTypes(): CreativeType[] {
    return Object.keys(CREATIVE_TYPES) as CreativeType[];
  },
};