import type { BrandMention, CrisisAlert, CrisisSeverity } from "../types";

function severityForRiskScore(riskScore: number): CrisisSeverity {
  return riskScore >= 70 ? "critical" : riskScore >= 45 ? "warning" : "info";
}

/**
 * Crisis alerts are generated by threshold checks over the live mention array on every
 * `generate()` call — replacing the 4 hand-authored fictional incidents in the legacy
 * `lib/brand-data.ts` (which never changed no matter what the real mentions showed). Three real
 * signals: per-platform negative-sentiment concentration, single-mention viral-negative reach
 * anomaly, and a complaint tag spreading across multiple platforms.
 */
export class CrisisDetectionRegistry {
  private resolvedIds = new Set<string>();

  generate(mentions: BrandMention[]): CrisisAlert[] {
    const alerts: CrisisAlert[] = [];
    if (mentions.length === 0) return alerts;

    const negative = mentions.filter(m => m.sentiment === "negative");
    const avgReach = mentions.reduce((sum, m) => sum + m.reach, 0) / mentions.length;

    // Signal 1: negative-sentiment concentration per platform.
    const platformGroups = new Map<string, BrandMention[]>();
    for (const mention of mentions) {
      const list = platformGroups.get(mention.platform) ?? [];
      list.push(mention);
      platformGroups.set(mention.platform, list);
    }
    for (const [platform, group] of platformGroups) {
      const negOnPlatform = group.filter(m => m.sentiment === "negative");
      const ratio = negOnPlatform.length / group.length;
      if (group.length >= 2 && ratio >= 0.4) {
        const reach = negOnPlatform.reduce((sum, m) => sum + m.reach, 0);
        const riskScore = Math.min(95, Math.round(ratio * 100 + negOnPlatform.length * 5));
        const id = `crisis-platform-${platform}`;
        alerts.push({
          id,
          title: `Negative sentiment concentrated on ${platform}`,
          description: `${negOnPlatform.length} of ${group.length} tracked mentions on ${platform} are negative (${Math.round(ratio * 100)}%) — well above a healthy baseline.`,
          severity: severityForRiskScore(riskScore),
          source: platform,
          mentionCount: negOnPlatform.length,
          reach,
          riskScore,
          detectedAt: new Date().toISOString(),
          isResolved: this.resolvedIds.has(id),
          recommendedAction: `Review the ${negOnPlatform.length} negative ${platform} mention${negOnPlatform.length === 1 ? "" : "s"} and prioritize a direct response to the highest-reach post.`,
        });
      }
    }

    // Signal 2: a single negative mention with far above-average reach (viral complaint).
    for (const mention of negative) {
      if (avgReach > 0 && mention.reach >= avgReach * 2.5) {
        const multiple = mention.reach / avgReach;
        const riskScore = Math.min(98, Math.round(60 + multiple * 5));
        const id = `crisis-viral-${mention.id}`;
        alerts.push({
          id,
          title: `Viral negative mention on ${mention.platform}`,
          description: `"${mention.content.slice(0, 90)}${mention.content.length > 90 ? "…" : ""}" from ${mention.author} has reached ${mention.reach.toLocaleString()} — ${multiple.toFixed(1)}x the average mention's reach.`,
          severity: severityForRiskScore(riskScore),
          source: mention.platform,
          mentionCount: 1,
          reach: mention.reach,
          riskScore,
          detectedAt: mention.detectedAt,
          isResolved: this.resolvedIds.has(id) || mention.isResolved,
          recommendedAction: `Respond directly to ${mention.author} and escalate to the response team — this mention's reach makes it a priority.`,
        });
      }
    }

    // Signal 3: the same complaint tag appearing, negatively, across 2+ platforms.
    const tagPlatforms = new Map<string, Set<string>>();
    const tagMentions = new Map<string, BrandMention[]>();
    for (const mention of negative) {
      for (const tag of mention.tags) {
        const platforms = tagPlatforms.get(tag) ?? new Set<string>();
        platforms.add(mention.platform);
        tagPlatforms.set(tag, platforms);
        const list = tagMentions.get(tag) ?? [];
        list.push(mention);
        tagMentions.set(tag, list);
      }
    }
    for (const [tag, platforms] of tagPlatforms) {
      if (platforms.size >= 2) {
        const group = tagMentions.get(tag) ?? [];
        const reach = group.reduce((sum, m) => sum + m.reach, 0);
        const riskScore = Math.min(90, Math.round(40 + platforms.size * 15 + group.length * 5));
        const id = `crisis-topic-${tag}`;
        alerts.push({
          id,
          title: `"${tag}" complaints spreading across channels`,
          description: `${group.length} negative mention${group.length === 1 ? "" : "s"} tagged "${tag}" detected across ${platforms.size} platforms: ${[...platforms].join(", ")}.`,
          severity: severityForRiskScore(riskScore),
          source: [...platforms].join(", "),
          mentionCount: group.length,
          reach,
          riskScore,
          detectedAt: new Date().toISOString(),
          isResolved: this.resolvedIds.has(id),
          recommendedAction: `Investigate the "${tag}" complaint pattern — recurring across multiple channels suggests a systemic issue rather than an isolated incident.`,
        });
      }
    }

    return alerts.sort((a, b) => b.riskScore - a.riskScore);
  }

  resolve(id: string): void {
    this.resolvedIds.add(id);
  }

  reopen(id: string): void {
    this.resolvedIds.delete(id);
  }
}

export const crisisDetectionRegistry = new CrisisDetectionRegistry();
